- hosts: cluster
  gather_facts: no
  tasks:
  - name: copying ssl cert into master
    copy: 
      src: /home/ssl/dex.pem
      dest: /etc/ssl/certs/dex.pem
  - name: api-edit
    shell: |
      sed -i '/- kube-apiserver/a\    \- --oidc-groups-claim=groups' test.yaml
      sed -i '/- kube-apiserver/a\    \- --oidc-username-claim=email' test.yaml
      sed -i '/- kube-apiserver/a\    \- --oidc-ca-file=/etc/ssl/certs/dex.pem' test.yaml
      sed -i '/- kube-apiserver/a\    \- --oidc-client-id=kubeapps':32000' test.yaml
      sed -i '/- kube-apiserver/a\    \- --oidc-issuer-url=https://'${MASTER_IP}':32000' test.yaml

